DATA SEGMENT 
ENTER DB 0AH,0DH,'$' 
MSG DB 0AH,0DH,'PLEASE INPUT A NUMBER (0--9):','$' 
seg7 db 3FH,06H,5BH,4FH,66H,6DH,7DH,07H,7FH,6FH；0-9 对应的段码 
DATA ENDS 
CODE SEGMENT 
ASSUME DS:DATA,CS:CODE 
START:MOV AX,DATA 
MOV DS,AX 
 MOV DX,028BH 
 MOV AL,80H 
 OUT DX,AL 
INPUT: MOV DX,OFFSET MSG 
 MOV AH,09H 
 INT 21H 
 MOV AH,01H;将数字回显 
 INT 21H 
 CMP AL,30H;将数字和 30H（0）作比较 
 JC FINISH ;若 AL 小于'0'（ASCII 值为 48）;则跳转到 FINISH 
 CMP AL,39H;将数字和 39H（9）作比较 
 JA FINISH;若 AL 大于'9'（ASCII 值为 57）则跳转到 FINISH 
 SUB AL,30H 
 MOV AH,0 
 MOV SI,AX 
 MOV DX,0288H 
 MOV AL,[SEG7+SI] 
 OUT DX,AL 
 JMP INPUT ;跳回 INPUT 
 FINISH: 
 MOV AH,4CH ;结束 
 INT 21H 
CODE ENDS ;代码段结束 
END START ;程序结束